/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.mcd.search;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertFalse;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import ru.nsu.fit.mcd.TestClass1;
import ru.nsu.fit.mcd.TestClass2;

class LibraryTest {

  private final TestClass2<Long, Integer> testClass = new TestClass2<>();
  private final TestClass1 testClass1 = new TestClass1();

  @Test
  void testClassScan() throws IOException {
    System.out.println(SearchCore.getClassReport(TestClass1.class));
  }

  @Test
  void test() {
    Arrays.stream(LibraryTest.class.getDeclaredFields()).forEach(
        field -> System.out.println(
            Arrays.stream(List.of(field.getGenericType()).toArray()).collect(Collectors.toList()))
    );
  }

  @Test
  void methodTest() throws IOException {
    ObjectMapper mapper = new ObjectMapper();

    System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(MethodSearchCore.getMethodsReport(TestClass1.class)));
  }
}
